# Generated by Django 5.2.5 on 2025-08-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_date_joined_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
