# Generated by Django 5.2.5 on 2025-08-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_mobile_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pin_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
